services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master Port
    volumes:
      - ~/DockerMount:/shared_data
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    volumes:
      - ~/DockerMount:/shared_data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2GB"

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    volumes:
      - ~/DockerMount:/shared_data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2GB"
