services:
  namenode:
    image: bde2020/hadoop-namenode
    container_name: namenode
    ports:
      - "9870:9870"  # Web UI
      - "9000:9000"  # RPC Port
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - namenode_data:/hadoop/dfs/name
      - ~/DockerMount:/shared_data
    networks:
      - hadoop-net

  datanode:
    image: bde2020/hadoop-datanode
    container_name: datanode
    depends_on:
      - namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - datanode_data:/hadoop/dfs/data
      - ~/DockerMount:/shared_data
    networks:
      - hadoop-net

networks:
  hadoop-net:

volumes:
  namenode_data:
  datanode_data:
